name: weddings
favicon: null
layout_spectrum: 0.9252615263685584
title: 'rojo foto//design :: Wedding Photography Serving the Chicagoland Area'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
typography_spectrum: 0.02095640473999083
